// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D inputTexture; 
RWStructuredBuffer <float3> depth;
int width;

[numthreads(32,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float4 col = inputTexture[id.xy];
	depth[id.x + id.y * width] = float3(id.x, id.y, float(col.r));
}
